sudo: false

language: node_js

node_js:
  - "6"

cache:
  directories:
    - $HOME/.cache/yarn

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn

script:
  - npm run build:ci

git:
  depth: 1

notifications:
  slack: akveo:q559HckfZMSyZRb803aiLcjH

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $4fd7c801fd18afd9246158e03abb00a32775f824 # Set in travis-ci.org dashboard
  on:
    branch: master